/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE DATABASE IF NOT EXISTS `od_networktv` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `od_networktv`;

CREATE TABLE IF NOT EXISTS `users_account` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(250) DEFAULT NULL,
  `EMAIL` varchar(150) DEFAULT NULL,
  `PASSWORD` varchar(256) DEFAULT NULL,
  `OTP` varchar(50) DEFAULT NULL,
  `YOUTUBE_CHANNEL_ID` varchar(150) DEFAULT NULL,
  `WALLET_BALANCE` float DEFAULT NULL,
  `WALLET_ID` varchar(25) DEFAULT NULL,
  `PROFILE_PIC` varchar(250) NOT NULL DEFAULT '/assets/profile/default.png',
  `IS_EXIST` varchar(50) DEFAULT 'true',
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `USERNAME` (`USERNAME`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

/*!40000 ALTER TABLE `users_account` DISABLE KEYS */;
INSERT INTO `users_account` (`USER_ID`, `USERNAME`, `EMAIL`, `PASSWORD`, `OTP`, `YOUTUBE_CHANNEL_ID`, `WALLET_BALANCE`, `WALLET_ID`, `PROFILE_PIC`, `IS_EXIST`) VALUES
	(1, 'ejayz', 'ajdapulangprovido@gmail.com', '$2b$10$QPgVnv/nbR0VwFkA.Law2.i7K1cKvfCwXBbLPQCYCwOnZBfMCtZ.e', NULL, 'UC9w8ssNRpCs78WaGsLJmX6A', 3, '8903041643081458143446636', '/assets/profile/default.png', 'true'),
	(2, 'johnny', 'stealthanonymous7@gmail.com', '$2b$10$QPgVnv/nbR0VwFkA.Law2.i7K1cKvfCwXBbLPQCYCwOnZBfMCtZ.e', NULL, 'UCgeaZHoqRgDgzVvueIehfkA', 0, '8162859933646058999890026', '/assets/profile/default.png', 'true');
/*!40000 ALTER TABLE `users_account` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `videos` (
  `VIDEO_ID` varchar(50) NOT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  `VIDEO_URL` varchar(50) DEFAULT NULL,
  `VIDEO_DETAILS` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`VIDEO_DETAILS`)),
  `VIDEO_VIEWS` int(11) DEFAULT NULL,
  `VIDEO_LIKES` int(11) DEFAULT NULL,
  `POSTED_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  `IS_EXIST` varchar(50) DEFAULT 'true',
  PRIMARY KEY (`VIDEO_ID`),
  KEY `FK_videos_users_account` (`USER_ID`),
  CONSTRAINT `FK_videos_users_account` FOREIGN KEY (`USER_ID`) REFERENCES `users_account` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*!40000 ALTER TABLE `videos` DISABLE KEYS */;
INSERT INTO `videos` (`VIDEO_ID`, `USER_ID`, `VIDEO_URL`, `VIDEO_DETAILS`, `VIDEO_VIEWS`, `VIDEO_LIKES`, `POSTED_DATE`, `IS_EXIST`) VALUES
	('1b893q0s6w5d', 1, 'https://www.youtube.com/watch?v=y9HK1iFiUK8', '{"publishedAt":"2022-07-12T11:24:05Z","channelId":"UC9w8ssNRpCs78WaGsLJmX6A","title":"KAY\\/0 Bucky Highlights #valorant #valoranthighlights #valorantmontage #valorantclips #valorantph","description":"I played my selected agent weapon of choice during character selection in valorant and I think it is OK to say it is well used lol. Anyways ,please like share and subscribe to my youtube channel !\\n\\nSubs!!!!1\\n\\nGet free overlays , enable multi stream with stream labs and many more feautures available to unlock with stream labs prime! check out this link and get 50% of when check out! \\n\\nhttps:\\/\\/streamlabs.com\\/goprime?promo=ejayz-7553-10\\n\\n\\nFind me in other platform:\\nTwitch:\\nhttps:\\/\\/twitch.tv\\/ejayztv\\nFacebook:\\nfacebook.com\\/ejayztv\\n\\nMusic Credit:\\nGreatest-Neffex\\nImortal-Neffex\\nLossing My Mind -Neffex\\nNeffex in soundcloud for No CopyRight Audios:\\nhttps:\\/\\/soundcloud.com\\/NEFFEXMUSIC","thumbnails":{"default":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/y9HK1iFiUK8\\/default.jpg","width":120,"height":90},"medium":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/y9HK1iFiUK8\\/mqdefault.jpg","width":320,"height":180},"high":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/y9HK1iFiUK8\\/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/y9HK1iFiUK8\\/sddefault.jpg","width":640,"height":480},"maxres":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/y9HK1iFiUK8\\/maxresdefault.jpg","width":1280,"height":720}},"channelTitle":"EjayzTv","tags":["valorant","valorantph","valorant highlights","valorant kay\\/0","valorant bucky","bucky highlights","ejayz","ejayztv","valorant kayo gameplay","valorant philipines","valorant bucky and kayo gameplay"],"categoryId":"20","liveBroadcastContent":"none","localized":{"title":"KAY\\/0 Bucky Highlights #valorant #valoranthighlights #valorantmontage #valorantclips #valorantph","description":"I played my selected agent weapon of choice during character selection in valorant and I think it is OK to say it is well used lol. Anyways ,please like share and subscribe to my youtube channel !\\n\\nSubs!!!!1\\n\\nGet free overlays , enable multi stream with stream labs and many more feautures available to unlock with stream labs prime! check out this link and get 50% of when check out! \\n\\nhttps:\\/\\/streamlabs.com\\/goprime?promo=ejayz-7553-10\\n\\n\\nFind me in other platform:\\nTwitch:\\nhttps:\\/\\/twitch.tv\\/ejayztv\\nFacebook:\\nfacebook.com\\/ejayztv\\n\\nMusic Credit:\\nGreatest-Neffex\\nImortal-Neffex\\nLossing My Mind -Neffex\\nNeffex in soundcloud for No CopyRight Audios:\\nhttps:\\/\\/soundcloud.com\\/NEFFEXMUSIC"}}', 5, 0, '2022-11-23 08:19:10', 'true'),
	('2uquq0esjexp', 1, 'https://www.youtube.com/watch?v=Oh2O_DBoyWA', '{"publishedAt":"2022-10-20T19:57:38Z","channelId":"UC9w8ssNRpCs78WaGsLJmX6A","title":"Dota Battle Pass Grind","description":"We are playing and trying to lvl up battle pass","thumbnails":{"default":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/Oh2O_DBoyWA\\/default.jpg","width":120,"height":90},"medium":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/Oh2O_DBoyWA\\/mqdefault.jpg","width":320,"height":180},"high":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/Oh2O_DBoyWA\\/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/Oh2O_DBoyWA\\/sddefault.jpg","width":640,"height":480},"maxres":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/Oh2O_DBoyWA\\/maxresdefault.jpg","width":1280,"height":720}},"channelTitle":"EjayzTv","tags":["Dota 2","Normal Match","Dota Battle Pass","Battle Pass","Lvl up","Gaming","Dota","TI","TI 11"],"categoryId":"20","liveBroadcastContent":"none","localized":{"title":"Dota Battle Pass Grind","description":"We are playing and trying to lvl up battle pass"},"defaultAudioLanguage":"en-US"}', 15, 0, '2022-10-25 21:39:15', 'true'),
	('a2x6dh82t8v2', 1, 'https://www.youtube.com/watch?v=CjaUrhHAxZc', '{"publishedAt":"2022-11-18T14:44:27Z","channelId":"UC9w8ssNRpCs78WaGsLJmX6A","title":"Hard Core Series Season 1 -Episode 1","description":"Hardcore or Normal survival ? Which should i do?\\n\\n\\nGet free stream overlays , enable multi stream  and many more feautures available to unlock with stream labs prime! check out this link and get 50% of when check out their annual $20 plan! \\n\\nhttps:\\/\\/streamlabs.com\\/goprime?promo=ejayz-7553-10\\n\\nSubscribe to the channel or follow me on other social media \\nTwitch : https:\\/\\/twitch.tv\\/ejayztv\\nFacebook : https:\\/\\/facebook.com\\/ejayztv\\n\\n\\nConsider tipping ?\\nSee it here : https:\\/\\/streamelements.com\\/ejayztv-521\\/tip\\n\\nIf you have suggestion comment bellow !\\n\\n\\n00:00 Announcement About normal survival \\n00:52 Objectives\\n01:11 Material Gathering\\n08:17 Building base\\n18:01 End","thumbnails":{"default":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/CjaUrhHAxZc\\/default.jpg","width":120,"height":90},"medium":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/CjaUrhHAxZc\\/mqdefault.jpg","width":320,"height":180},"high":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/CjaUrhHAxZc\\/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/CjaUrhHAxZc\\/sddefault.jpg","width":640,"height":480},"maxres":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/CjaUrhHAxZc\\/maxresdefault.jpg","width":1280,"height":720}},"channelTitle":"EjayzTv","tags":["minecraft season 1","minecraft season 1 episode 1","minecraft season 1 ep 1","minecraft season 10","minecraft hardcore lets play","minecraft lets play","minecraft lets play 1.19","minecraft lets play episode 1","minecraft lets play ep 1","minecraft 1.19 lets play","minecraft 1.19 lets play ep 1","minecraft 1.19 lets play fwhip","minecraft 1.19 lets play survival","minecraft hardcore series"],"categoryId":"20","liveBroadcastContent":"none","localized":{"title":"Hard Core Series Season 1 -Episode 1","description":"Hardcore or Normal survival ? Which should i do?\\n\\n\\nGet free stream overlays , enable multi stream  and many more feautures available to unlock with stream labs prime! check out this link and get 50% of when check out their annual $20 plan! \\n\\nhttps:\\/\\/streamlabs.com\\/goprime?promo=ejayz-7553-10\\n\\nSubscribe to the channel or follow me on other social media \\nTwitch : https:\\/\\/twitch.tv\\/ejayztv\\nFacebook : https:\\/\\/facebook.com\\/ejayztv\\n\\n\\nConsider tipping ?\\nSee it here : https:\\/\\/streamelements.com\\/ejayztv-521\\/tip\\n\\nIf you have suggestion comment bellow !\\n\\n\\n00:00 Announcement About normal survival \\n00:52 Objectives\\n01:11 Material Gathering\\n08:17 Building base\\n18:01 End"},"defaultAudioLanguage":"en"}', 4, 0, '2022-11-21 21:08:15', 'true'),
	('bz1hjztbofjk', 1, 'https://www.youtube.com/watch?v=QBxCb0ovZeg', '{"publishedAt":"2022-10-24T12:07:28Z","channelId":"UC9w8ssNRpCs78WaGsLJmX6A","title":"Battle Pass 2022 Treasure Opening 3","description":"While we grinding we got another lvl and another treasure . But still luck is not on our side.\\n\\nGet free stream overlays , enable multi stream  and many more feautures available to unlock with stream labs prime! check out this link and get 50% of when check out their annual $20 plan! \\n\\nhttps:\\/\\/streamlabs.com\\/goprime?promo=ejayz-7553-10\\n\\nSubscribe to the channel or follow me on other social media \\nTwitch : https:\\/\\/twitch.tv\\/ejayztv\\nFacebook : https:\\/\\/facebook.com\\/ejayztv\\n\\n\\nConsider tipping ?\\nSee it here : https:\\/\\/streamelements.com\\/ejayztv-521\\/tip\\n\\nIf you have suggestion comment bellow !","thumbnails":{"default":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/QBxCb0ovZeg\\/default.jpg","width":120,"height":90},"medium":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/QBxCb0ovZeg\\/mqdefault.jpg","width":320,"height":180},"high":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/QBxCb0ovZeg\\/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/QBxCb0ovZeg\\/sddefault.jpg","width":640,"height":480},"maxres":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/QBxCb0ovZeg\\/maxresdefault.jpg","width":1280,"height":720}},"channelTitle":"EjayzTv","tags":["Dota 2","Dota 2 battle pass","battle pass 2022","dota 2 try hard","dota 2 treasure","huskar","ti 11","ti 12","ti 13"],"categoryId":"20","liveBroadcastContent":"none","localized":{"title":"Battle Pass 2022 Treasure Opening 3","description":"While we grinding we got another lvl and another treasure . But still luck is not on our side.\\n\\nGet free stream overlays , enable multi stream  and many more feautures available to unlock with stream labs prime! check out this link and get 50% of when check out their annual $20 plan! \\n\\nhttps:\\/\\/streamlabs.com\\/goprime?promo=ejayz-7553-10\\n\\nSubscribe to the channel or follow me on other social media \\nTwitch : https:\\/\\/twitch.tv\\/ejayztv\\nFacebook : https:\\/\\/facebook.com\\/ejayztv\\n\\n\\nConsider tipping ?\\nSee it here : https:\\/\\/streamelements.com\\/ejayztv-521\\/tip\\n\\nIf you have suggestion comment bellow !"}}', 3, 0, '2022-10-25 21:39:56', 'true'),
	('iwws41tbm243', 2, 'https://www.youtube.com/watch?v=6maj3hFYGEo', '{"publishedAt":"2019-04-02T09:53:30Z","channelId":"UCgeaZHoqRgDgzVvueIehfkA","title":"How to mirana in turbo.","description":"Playing mirana in turbo mode\\nlike subscribe and share\\nSubscribe to my second channel\\nhttps:\\/\\/www.youtube.com\\/channel\\/UCipfjSkDmYxIrz6pYX6y4Jw","thumbnails":{"default":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/6maj3hFYGEo\\/default.jpg","width":120,"height":90},"medium":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/6maj3hFYGEo\\/mqdefault.jpg","width":320,"height":180},"high":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/6maj3hFYGEo\\/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/6maj3hFYGEo\\/sddefault.jpg","width":640,"height":480},"maxres":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/6maj3hFYGEo\\/maxresdefault.jpg","width":1280,"height":720}},"channelTitle":"GENERAL FY GAMING","tags":["mirana","dota2","wtf moment","wtf","comeback","viper","earthshaker","gaming","generaljuude gaming","playing","juude","turbo mode","cancer","pinoys"],"categoryId":"20","liveBroadcastContent":"none","localized":{"title":"How to mirana in turbo.","description":"Playing mirana in turbo mode\\nlike subscribe and share\\nSubscribe to my second channel\\nhttps:\\/\\/www.youtube.com\\/channel\\/UCipfjSkDmYxIrz6pYX6y4Jw"}}', 3, 0, '2022-12-12 23:50:39', 'true'),
	('j6tuzksx4fi7', 1, 'https://www.youtube.com/watch?v=sV21U0c84X4', '{"publishedAt":"2022-10-19T15:09:26Z","channelId":"UC9w8ssNRpCs78WaGsLJmX6A","title":"Opening Another Battle Pass 2022 Treasure","description":"Ey another treasure opening . Although it is just only one but it is still ok . Please sub and like the video thanks!\\n\\nGet free stream overlays , enable multi stream  and many more feautures available to unlock with stream labs prime! check out this link and get 50% of when check out their annual $20 plan! Yes ! You will just pay $10 on check out!\\n\\nStream Labs Prime\\nhttps:\\/\\/streamlabs.com\\/goprime?promo=ejayz-7553-10\\n\\nSubscribe to the channel or follow me on other social media \\nTwitch : https:\\/\\/twitch.tv\\/ejayztv\\nFacebook : https:\\/\\/facebook.com\\/ejayztv\\n\\n\\nConsider tipping ?\\nSee it here : https:\\/\\/streamelements.com\\/ejayztv-521\\/tip\\n\\nIf you have suggestion comment bellow !","thumbnails":{"default":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/sV21U0c84X4\\/default.jpg","width":120,"height":90},"medium":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/sV21U0c84X4\\/mqdefault.jpg","width":320,"height":180},"high":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/sV21U0c84X4\\/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/sV21U0c84X4\\/sddefault.jpg","width":640,"height":480}},"channelTitle":"EjayzTv","tags":["Dota 2","Treasures","opening of treasures","dota battle pass","preview","dota battle pass 2022 preview","opening of battle pass","dota battle pass opening","ejayz","ejayz tv","ejayz stream","dota plus","dota bundle","imortals","dota 2 imortals"],"categoryId":"20","liveBroadcastContent":"none","localized":{"title":"Opening Another Battle Pass 2022 Treasure","description":"Ey another treasure opening . Although it is just only one but it is still ok . Please sub and like the video thanks!\\n\\nGet free stream overlays , enable multi stream  and many more feautures available to unlock with stream labs prime! check out this link and get 50% of when check out their annual $20 plan! Yes ! You will just pay $10 on check out!\\n\\nStream Labs Prime\\nhttps:\\/\\/streamlabs.com\\/goprime?promo=ejayz-7553-10\\n\\nSubscribe to the channel or follow me on other social media \\nTwitch : https:\\/\\/twitch.tv\\/ejayztv\\nFacebook : https:\\/\\/facebook.com\\/ejayztv\\n\\n\\nConsider tipping ?\\nSee it here : https:\\/\\/streamelements.com\\/ejayztv-521\\/tip\\n\\nIf you have suggestion comment bellow !"}}', 1, 0, '2022-10-25 21:39:34', 'true'),
	('nj62bmb1xyoe', 1, 'https://www.youtube.com/watch?v=XjPXAgx5EwA', '{"publishedAt":"2022-09-19T14:35:00Z","channelId":"UC9w8ssNRpCs78WaGsLJmX6A","title":"Just cutting trees-Twitch Stream vods","description":"Hi ,uploading this twitch live and probably upload other videos .But it depend on how big the file is .\\n\\nGet free overlays , enable multi stream with stream labs and many more feautures available to unlock with stream labs prime! check out this link and get 50% of when check out! \\n\\nhttps:\\/\\/streamlabs.com\\/goprime?promo=ejayz-7553-10\\n\\nSubscribe to the channel or follow me on other social media \\nTwitch : https:\\/\\/twitch.tv\\/ejayztv\\nFacebook : https:\\/\\/facebook.com\\/ejayztv\\n\\n\\nConsider tipping ?\\nSee it here : https:\\/\\/streamelements.com\\/ejayztv-521\\/tip\\n\\n\\nIf you have suggestion comment bellow !","thumbnails":{"default":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/XjPXAgx5EwA\\/default.jpg","width":120,"height":90},"medium":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/XjPXAgx5EwA\\/mqdefault.jpg","width":320,"height":180},"high":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/XjPXAgx5EwA\\/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https:\\/\\/i.ytimg.com\\/vi\\/XjPXAgx5EwA\\/sddefault.jpg","width":640,"height":480}},"channelTitle":"EjayzTv","tags":["minecraft","minecrafters","vod","twitch vod","minecraft twitch","streamer","ejayz","survival","playing survival minecraft"],"categoryId":"20","liveBroadcastContent":"none","localized":{"title":"Just cutting trees-Twitch Stream vods","description":"Hi ,uploading this twitch live and probably upload other videos .But it depend on how big the file is .\\n\\nGet free overlays , enable multi stream with stream labs and many more feautures available to unlock with stream labs prime! check out this link and get 50% of when check out! \\n\\nhttps:\\/\\/streamlabs.com\\/goprime?promo=ejayz-7553-10\\n\\nSubscribe to the channel or follow me on other social media \\nTwitch : https:\\/\\/twitch.tv\\/ejayztv\\nFacebook : https:\\/\\/facebook.com\\/ejayztv\\n\\n\\nConsider tipping ?\\nSee it here : https:\\/\\/streamelements.com\\/ejayztv-521\\/tip\\n\\n\\nIf you have suggestion comment bellow !"}}', 1, 0, '2022-10-25 08:34:45', 'true');
/*!40000 ALTER TABLE `videos` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
