import Head from 'next/head'

export default function Page() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen flex flex-row overflow-hidden background">
        <div className="mx-auto my-auto w-2/5 h-full background-container shadow-2xl">
          
        </div>
        <div className="mx-auto my-auto w-full h-full background-container shadow-inner shadow-2xl">
          
          </div>
      </main>
    </>
  )
}