"use client"
import Head from "next/head";
import Image from "next/image";
import React,{useSelector, useDispatch} from 'react-redux'
import {get_authholder,set_authholder} from "./auth_holder"
import { RootState } from "../store/store";
import { update_token } from "../store/reducers/authtokenReducer";

export default function Page() {

  const auth=useSelector((state:RootState)=>state.authtokenReducer.value)
  const dispatch=useDispatch()

  console.log(auth)
const LoginUser=async(event:any)=>{
  event.preventDefault()
  let headersList = {
    "Accept": "*/*",
    "User-Agent": "Thunder Client (https://www.thunderclient.com)",
    "Content-Type": "application/json"
   }
   
   let bodyContent = JSON.stringify({
     "email":event.target.email.value,
     "password":event.target.password.value,
     "remember_me":event.target.remember_me.value
   });
   let response = await fetch("http://localhost:3000/api/login", { 
     method: "POST",
     body: bodyContent,
     headers: headersList
   });
   
   let data = await response.text();
   
   console.log(data)
    dispatch(update_token(data))
    console.log("auth:"+auth)
  }
  return (
    <>
 
      <Head>
        <title>Login OdNetwork.Tv</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen flex flex-row overflow-x-auto lg:overflow-hidden background">
      <section className="h-screen">
  <div className="container  px-6 py-12 h-full">
    <div className="flex justify-center items-center flex-wrap h-full g-6 text-gray-800">
      <div className="md:w-8/12 lg:w-6/12 mb-12 md:mb-0">
        <img
          src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.svg"
          className="w-full"
          alt="Phone image"
        />
      </div>
      <div className="md:w-8/12 h-auto bg-white p-4 rounded-md text-black lg:w-5/12 lg:ml-20">
        <form onSubmit={LoginUser}>
          <div className="w-full h-12 mt-2 mb-4 text-2xl font-bold">
            Login on Od Network Tv
          </div>
          <div className="mb-6">
            <input
              type="text"
              className="form-control block w-full px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
              id="email"
              name="email"
              placeholder="Email address"
            />
          </div>
          <div className="mb-6">
            <input
              type="password"
              className="form-control block w-full px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
              placeholder="Password"
              id="password"
              name="password"
            />
          </div>

          <div className="flex justify-between items-center mb-6">
            <div className="form-group form-check">
              <input
                type="checkbox"
                className="form-check-input appearance-none h-4 w-4 border border-gray-300 rounded-sm bg-white checked:bg-blue-600 checked:border-blue-600 focus:outline-none transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer"
                defaultChecked
                id="remember_me"
                name="remember_me"
              />
              <label className="form-check-label inline-block text-gray-800" htmlFor="remember_me"
                >Remember me</label
              >
            </div>
            <a
              href="#!"
              className="text-blue-600 hover:text-blue-700 focus:text-blue-700 active:text-blue-800 duration-200 transition ease-in-out"
              >Forgot password?</a
            >
          </div>
          <button type="submit"  className="inline-block px-7 py-3 bg-blue-600 text-white font-medium text-sm leading-snug uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out w-full" data-mdb-ripple="true" data-mdb-ripple-color="light">
            Sign in
          </button>
          </form>
      </div>
    </div>
  </div>
  
</section>
      </main>
   
    </>
  );
}

